### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by dncortez** [alcazar90/rock-glacier-detection#2]
Los TO DO principales para hacer ASAP.

1.- Obtener imágenes satelitales. No es necesario por ahora que calcen en la misma matriz de velocidades, pero sí que contengan los glaciares de roca (pueden ser por separado). 
2.- Hacer el EDA en base a velocidad y ojalá también imágenes satelitales.
3.- Hacer la presentación
4.- Ojalá entrenar un primer modelo dummy overfitteado

**Comment by alcazar90** [comment]
Listo! buen trabajo a todos :D
